# -*- coding: utf-8 -*-
"""TCN_model_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v7ivDm8w1EWvfULaTJ6tn0ONCf1BNDzd
"""

import datetime

def to_milliseconds(dt):
    return int(dt.timestamp() * 1000)

end_time = datetime.datetime.utcnow()
start_time = end_time - datetime.timedelta(days=180)

start_ms = to_milliseconds(start_time)
end_ms = to_milliseconds(end_time)

import requests
import time
import pandas as pd

BASE_URL = "https://api.binance.us/api/v3/klines"

def get_klines(symbol, interval, start_time, end_time):
    all_klines = []

    while start_time < end_time:
        params = {
            "symbol": symbol,
            "interval": interval,
            "startTime": start_time,
            "endTime": end_time,
            "limit": 1000
        }

        response = requests.get(BASE_URL, params=params)
        data = response.json()

        if not data:
            break

        all_klines.extend(data)

        # move start_time forward
        start_time = data[-1][0] + 1

        time.sleep(0.2)  # avoid rate limits

    return all_klines

raw_data = get_klines(
    symbol="BTCUSDT",
    interval="5m",
    start_time=start_ms,
    end_time=end_ms
)

columns = [
    "open_time", "open", "high", "low", "close", "volume",
    "close_time", "quote_asset_volume", "number_of_trades",
    "taker_buy_base_volume", "taker_buy_quote_volume", "ignore"
]

df = pd.DataFrame(raw_data, columns=columns)

# Convert types
df["open_time"] = pd.to_datetime(df["open_time"], unit="ms")
df["close_time"] = pd.to_datetime(df["close_time"], unit="ms")

for col in ["open", "high", "low", "close", "volume"]:
    df[col] = df[col].astype(float)

# Sort & reset index
df = df.sort_values("open_time").reset_index(drop=True)

df.to_csv("/content/drive/MyDrive/TCN/BTCUSDT_5m_6months.csv", index=False)

import numpy as np

def compute_atr(df, period=14):
    high = df['high']
    low = df['low']
    close = df['close']

    prev_close = close.shift(1)

    tr = pd.concat([
        high - low,
        (high - prev_close).abs(),
        (low - prev_close).abs()
    ], axis=1).max(axis=1)

    atr = tr.rolling(period).mean()
    return atr

def compute_rsi(df, period=14):
    delta = df['close'].diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    avg_gain = gain.rolling(period).mean()
    avg_loss = loss.rolling(period).mean()

    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

df['atr'] = compute_atr(df)
df['rsi'] = compute_rsi(df)

df['is_swing_high'] = False

for i in range(1, len(df) - 1):
    if df.loc[i, 'high'] > df.loc[i-1, 'high'] and df.loc[i, 'high'] > df.loc[i+1, 'high']:
        df.loc[i, 'is_swing_high'] = True

resistances = []

for i in range(len(df)):
    if df.loc[i, 'is_swing_high']:
        resistances.append({
            "price": df.loc[i, 'high'],
            "index": i,
            "touches": 1,
            "last_touch": i
        })

MAX_AGE = 200  # candles

def nearest_resistance(idx, close_price):
    valid = []
    for r in resistances:
        if r["price"] > close_price and (idx - r["index"]) <= MAX_AGE:
            valid.append(r)

    if not valid:
        return None

    return min(valid, key=lambda r: r["price"])

df['dist_to_resistance'] = np.nan
df['resistance_age'] = np.nan
df['resistance_touches'] = np.nan
df['resistance_price'] = np.nan

for i in range(len(df)):
    r = nearest_resistance(i, df.loc[i, 'close'])

    if r is None:
        # No resistance overhead
        df.loc[i, 'resistance_price'] = np.nan
        df.loc[i, 'dist_to_resistance'] = 5.0
        df.loc[i, 'resistance_age'] = 1.0
        df.loc[i, 'resistance_touches'] = 0.0
    else:
        atr = df.loc[i, 'atr']

        df.loc[i, 'resistance_price'] = r['price']
        df.loc[i, 'dist_to_resistance'] = (df.loc[i, 'close'] - r['price']) / (atr + 1e-6)
        df.loc[i, 'resistance_age'] = (i - r['index']) / MAX_AGE
        df.loc[i, 'resistance_touches'] = min(r['touches'] / 5, 1.0)

features = [
    'open', 'high', 'low', 'close', 'volume',
    'rsi', 'atr',
    'dist_to_resistance',
    'resistance_age',
    'resistance_touches'
]
df[features].shape
df[['close', 'dist_to_resistance']].iloc[-500:].plot(subplots=True)
df.to_csv("/content/drive/MyDrive/TCN/resistance.csv", index=False)

import numpy as np
import pandas as pd

# -----------------------------
# Configuration
# -----------------------------
K = 10                 # prediction horizon (candles)
ATR_BREAK = 1.0          # breakout tolerance
ATR_CONTINUE = 1.0    # continuation threshold


# -----------------------------
# Label functions
# -----------------------------
def label_breakout(df, t, resistance, atr):
    future_close = df['close'].iloc[t+1 : t+K+1]
    future_open  = df['open'].iloc[t+1 : t+K+1]

    return int(
        (future_close > resistance + 1.0 * atr).any()
        and (future_open < resistance).any()
    )


def label_retest(df, t, resistance, atr):
    future_low = df['low'].iloc[t+1 : t+K+1]
    return int(future_low.min() <= resistance + ATR_BREAK * atr)


def label_continuation(df, t, resistance, atr):
    future_high = df['high'].iloc[t+K+1 : t+2*K+1]
    return int(future_high.max() > resistance + ATR_CONTINUE * atr)


def label_move_size(df, t, resistance, atr):
    future_high = df['high'].iloc[t+1 : t+2*K+1]
    move = (future_high.max() - resistance) / atr
    return np.clip(move, -5.0, 5.0)


# -----------------------------
# Main label creation loop
# -----------------------------
labels = []

for t in range(len(df)):

    # Ensure future data exists
    if t + 2*K >= len(df):
        continue

    resistance = df['resistance_price'].iloc[t]
    atr = df['atr'].iloc[t]

    # Skip if resistance or ATR is missing
    if pd.isna(resistance) or pd.isna(atr) or atr == 0:
        continue

    breakout = label_breakout(df, t, resistance, atr)

    if breakout:
        retest = label_retest(df, t, resistance, atr)
    else:
        retest = 0

    if retest:
        continuation = label_continuation(df, t, resistance, atr)
    else:
        continuation = 0

    move_size = label_move_size(df, t, resistance, atr)

    labels.append({
        "t": t,
        "breakout": breakout,
        "retest": retest,
        "continuation": continuation,
        "move_size": move_size
    })


# -----------------------------
# Convert to DataFrame
# -----------------------------
labels_df = pd.DataFrame(labels)
labels_df.to_csv("/content/drive/MyDrive/TCN/labels.csv", index=False)
print(labels_df.head())

import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/TCN/resistance.csv")
labels_df = pd.read_csv("/content/drive/MyDrive/TCN/labels.csv")

df = df.reset_index(drop=True)
labels_df["t"] = labels_df["t"].astype(int)

labels_aligned = labels_df.set_index("t")[
    ["breakout", "retest", "continuation", "move_size"]
]

df = df.join(labels_aligned, how="left")

def create_sliding_windows(df, feature_cols, label_cols, lookback=200):

    X, y = [], []

    # 🔑 Extract once (IMPORTANT)
    feature_array = df[feature_cols].values
    label_array = df[label_cols].values

    for t in range(lookback - 1, len(df)):

        # skip unlabeled rows
        if np.isnan(label_array[t]).any():
            continue

        x_window = feature_array[
            t - lookback + 1 : t + 1
        ]

        y_target = label_array[t]

        X.append(x_window)
        y.append(y_target)

    X = np.array(X, dtype=np.float32)
    y = np.array(y, dtype=np.float32)

    return X, y

FEATURE_COLS = [
    "open", "high", "low", "close", "volume",
    "rsi", "atr",
    "dist_to_resistance",
    "resistance_age",
    "resistance_touches"
]

LABEL_COLS = [
    "breakout",
    "retest",
    "continuation",
    "move_size"
]

LOOKBACK = 200

X, y = create_sliding_windows(
    df=df,
    feature_cols=FEATURE_COLS,
    label_cols=LABEL_COLS,
    lookback=LOOKBACK
)
np.save("/content/drive/MyDrive/TCN/X.npy", X)
np.save("/content/drive/MyDrive/TCN/y.npy", y)
print("X shape:", X.shape)
print("y shape:", y.shape)

import torch
import torch.nn as nn
import torch.nn.functional as F

class TemporalBlock(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, dilation, dropout):
        super().__init__()

        padding = (kernel_size - 1) * dilation

        self.conv1 = nn.Conv1d(
            in_channels,
            out_channels,
            kernel_size,
            padding=padding,
            dilation=dilation
        )
        self.conv2 = nn.Conv1d(
            out_channels,
            out_channels,
            kernel_size,
            padding=padding,
            dilation=dilation
        )

        self.dropout = nn.Dropout(dropout)
        self.relu = nn.ReLU()

        # Match channels for residual
        self.downsample = (
            nn.Conv1d(in_channels, out_channels, 1)
            if in_channels != out_channels
            else None
        )

    def forward(self, x):
        out = self.conv1(x)
        out = out[:, :, :-self.conv1.padding[0]]  # causal trim
        out = self.relu(out)
        out = self.dropout(out)

        out = self.conv2(out)
        out = out[:, :, :-self.conv2.padding[0]]  # causal trim
        out = self.relu(out)
        out = self.dropout(out)

        res = x if self.downsample is None else self.downsample(x)
        return self.relu(out + res)

class TemporalConvNet(nn.Module):
    def __init__(self, num_inputs, num_channels, kernel_size=3, dropout=0.1):
        super().__init__()

        layers = []
        num_levels = len(num_channels)

        for i in range(num_levels):
            dilation = 2 ** i
            in_ch = num_inputs if i == 0 else num_channels[i - 1]
            out_ch = num_channels[i]

            layers.append(
                TemporalBlock(
                    in_channels=in_ch,
                    out_channels=out_ch,
                    kernel_size=kernel_size,
                    dilation=dilation,
                    dropout=dropout
                )
            )

        self.network = nn.Sequential(*layers)

    def forward(self, x):
        return self.network(x)

class TradingTCN(nn.Module):
    def __init__(self, num_features):
        super().__init__()

        self.tcn = TemporalConvNet(
            num_inputs=num_features,
            num_channels=[64]*7,
            kernel_size=3,
            dropout=0.1
        )

        self.breakout_head = nn.Linear(64, 1)
        self.retest_head = nn.Linear(64, 1)
        self.cont_head = nn.Linear(64, 1)
        self.move_head = nn.Linear(64, 1)

    def forward(self, x):
        """
        x shape: (batch, features, time)
        """

        y = self.tcn(x)          # (batch, 64, time)
        last = y[:, :, -1]       # last timestep (batch, 64)

        breakout = self.breakout_head(last)       # logits
        retest = self.retest_head(last)
        continuation = self.cont_head(last)
        move_size = self.move_head(last)

        return breakout, retest, continuation, move_size

import torch
import numpy as np
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader
import os # Import os module

# Ensure the data directory exists
os.makedirs('data/processed', exist_ok=True)

X = np.load("/content/drive/MyDrive/TCN/X.npy")
y = np.load("/content/drive/MyDrive/TCN/y.npy")


# --------------------------------------------------
# 1. Device
# --------------------------------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# --------------------------------------------------
# 2. Convert NumPy → Torch
# --------------------------------------------------
X = np.transpose(X, (0, 2, 1))
mask = np.isfinite(X).all(axis=(1,2)) & np.isfinite(y).all(axis=1)
X = X[mask]
y = y[mask]

print("Breakout rate:", y[:, 0].mean())
print("Retest rate:", y[:, 1].mean())
print("Continuation rate:", y[:, 2].mean())
print("Move size mean/std:", y[:, 3].mean(), y[:, 3].std())

X_tensor = torch.tensor(X, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.float32)

# --------------------------------------------------
# 3. Time-based Train / Validation Split
# --------------------------------------------------
split_ratio = 0.8
split_idx = int(len(X_tensor) * split_ratio)

X_train = X_tensor[:split_idx]
y_train = y_tensor[:split_idx]

X_val = X_tensor[split_idx:]
y_val = y_tensor[split_idx:]

print("Train samples:", len(X_train))
print("Val samples:", len(X_val))

# --------------------------------------------------
# 4. DataLoaders
# --------------------------------------------------
BATCH_SIZE = 64

train_loader = DataLoader(
    TensorDataset(X_train, y_train),
    batch_size=BATCH_SIZE,
    shuffle=False
)

val_loader = DataLoader(
    TensorDataset(X_val, y_val),
    batch_size=BATCH_SIZE,
    shuffle=False
)

model = TradingTCN(num_features=X.shape[1])
model.to(device)

# --------------------------------------------------
# 6. Loss Functions
# --------------------------------------------------
pos_weight = torch.tensor([5.0], device=device)

bce = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
mse = nn.MSELoss()           # for move_size

# --------------------------------------------------
# 7. Optimizer
# --------------------------------------------------
optimizer = torch.optim.Adam(model.parameters(), lr=3e-4)

# --------------------------------------------------
# 8. Training Loop
# --------------------------------------------------
EPOCHS = 20

for epoch in range(EPOCHS):

    # -------- TRAIN --------
    model.train()
    train_loss = 0.0

    for xb, yb in train_loader:
        xb = xb.to(device)
        yb = yb.to(device)

        optimizer.zero_grad()

        # Forward pass
        breakout_logits, retest_logits, cont_logits, move_pred = model(xb)

        # Loss per head
        loss_breakout = bce(breakout_logits.squeeze(), yb[:, 0])
        loss_retest   = bce(retest_logits.squeeze(),   yb[:, 1])
        loss_cont     = bce(cont_logits.squeeze(),     yb[:, 2])
        loss_move     = mse(move_pred.squeeze(),       yb[:, 3])

        # Total loss
        loss = (
            loss_breakout +
            loss_retest +
            loss_cont +
            0.01 * loss_move
        )

        # Backprop
        loss.backward()

        # Gradient clipping (important for stability)
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        optimizer.step()

        train_loss += loss.item()

    train_loss /= len(train_loader)

    # -------- VALIDATION --------
    model.eval()
    val_loss = 0.0

    with torch.no_grad():
        for xb, yb in val_loader:
            xb = xb.to(device)
            yb = yb.to(device)

            breakout_logits, retest_logits, cont_logits, move_pred = model(xb)

            loss = (
                bce(breakout_logits.squeeze(), yb[:, 0]) +
                bce(retest_logits.squeeze(),   yb[:, 1]) +
                bce(cont_logits.squeeze(),     yb[:, 2]) +
                mse(move_pred.squeeze(),       yb[:, 3])
            )

            val_loss += loss.item()

    val_loss /= len(val_loader)

    print(
        f"Epoch {epoch+1:02d}/{EPOCHS} | "
        f"Train Loss: {train_loss:.4f} | "
        f"Val Loss: {val_loss:.4f}"
    )

# --------------------------------------------------
# 9. Save Model
# --------------------------------------------------
torch.save(model.state_dict(), "/content/drive/MyDrive/TCN/trading_tcn.pth")
print("✅ Model saved to /content/drive/MyDrive/TCN/trading_tcn.pth")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

WINDOW = 200
NUM_FEATURES = 10   # MUST match training exactly

model = TradingTCN(num_features=NUM_FEATURES).to(device)
model.load_state_dict(torch.load("/content/drive/MyDrive/TCN/trading_tcn.pth"))
model.eval()

from collections import deque
feature_buffer = deque(maxlen=WINDOW)
def generate_dummy_candle(prev_price):
    change = np.random.normal(0, 0.001)  # small random move
    close = prev_price * (1 + change)

    high = close * (1 + abs(np.random.normal(0, 0.0005)))
    low  = close * (1 - abs(np.random.normal(0, 0.0005)))
    volume = np.random.uniform(100, 500)

    return {
        "close": close,
        "high": high,
        "low": low,
        "volume": volume
    }

def build_feature_vector(candle):
    # Dummy indicator values
    atr = 50.0
    resistance_price = 43000.0

    distance_to_res = (candle["close"] - resistance_price) / atr

    return [
        candle["close"],
        candle["high"],
        candle["low"],
        candle["volume"],
        atr,
        distance_to_res,
        0.0,  # rsi placeholder
        0.0,  # resistance_age
        1.0,  # resistance_touches
        0.0   # padding if needed
    ]

price = 43000.0

for step in range(300):   # simulate 300 candles

    candle = generate_dummy_candle(price)
    price = candle["close"]

    features = build_feature_vector(candle)
    feature_buffer.append(features)

    if len(feature_buffer) < WINDOW:
        continue  # wait until buffer is full

    # Prepare model input
    X_live = np.array(feature_buffer)          # (200, F)
    X_live = X_live.T                          # (F, 200)
    X_live = X_live[np.newaxis, :, :]          # (1, F, 200)
    X_live = torch.tensor(X_live, dtype=torch.float32).to(device)

    # Inference
    with torch.no_grad():
        b, r, c, m = model(X_live)

    breakout_p = torch.sigmoid(b).item()
    retest_p   = torch.sigmoid(r).item()
    cont_p     = torch.sigmoid(c).item()
    move_size  = m.item()

    print(
        f"[Candle {step}] "
        f"Breakout: {breakout_p:.2f} | "
        f"Retest: {retest_p:.2f} | "
        f"Continue: {cont_p:.2f} | "
        f"Move: {move_size:.2f} ATR"
    )

from google.colab import drive
drive.mount('/content/drive')

